### ISSUE TITLE
Can't printer khmer language 

### ISSUE THREAD

**Issue by brahimkh** [arthas1888/flutter_pos_printer_platform#33]
An issue below:
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "សូមស្វាគមន"
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      Generator._encode (package:flutter_pos_printer_platform/esc_pos_utils_platform/src/generator.dart:70:21)
#3      Generator.row (package:flutter_pos_printer_platform/esc_pos_utils_platform/src/generator.dart:582:89)
#4      _MyAppState._printReceiveTest (package:flutter_pos_printer_example/main.dart:186:24)
<asynchronous suspension>

**Comment by arthas1888** [comment]
the generator library is not mine, open the issue in the correct repo
