### ISSUE TITLE
Can't print in lao and thai lang please help 

### ISSUE THREAD

**Issue by Seng555** [arthas1888/flutter_pos_printer_platform#34]
D/BluetoothPrinter(16174): deviceName InnerPrinter deviceHardwareAddress 00:11:22:33:44:55
I/flutter (16174): InnerPrinter
E/flutter (16174): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "ສະບາຍດີ"
E/flutter (16174): #0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
E/flutter (16174): #1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
E/flutter (16174): #2      Generator._encode (package:esc_pos_utils/src/generator.dart:77:21)
E/flutter (16174): #3      Generator.text (package:esc_pos_utils/src/generator.dart:354:9)
E/flutter (16174): #4      _MyHomePageState._printReceiveTest (package:flutter_printer/main.dart:339:24)
E/flutter (16174): <asynchronous suspension>
E/flutter (16174):

**Comment by arthas1888** [comment]
the generator lib is not mine open the issue in the correct repo

**Comment by Johnny-Luu** [comment]
@Seng555 do you still need help? if so, please upload your code
